Accept user prompt "Enter username: ";

-- USER SQL
CREATE USER &user IDENTIFIED BY &user;
DEFAULT TABLESPACE USERS;
TEMPORARY TABLESPACE TEMP;

-- QUOTAS
ALTER USER &user QUOTA UNLIMITED ON INDX;
ALTER USER &user QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT CONNECT TO &user;
GRANT RESOURCE TO &user;
ALTER USER &user DEFAULT ROLE CONNECT, RESOURCE;

-- SYSTEM PRIVILEGES
GRANT CREATE VIEW TO &user;
GRANT CREATE SYNONYM TO &user;